# Generated by Django 5.1.3 on 2024-11-21 17:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ExpenseSystem', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='category',
            name='description',
        ),
        migrations.RemoveField(
            model_name='expense',
            name='created_at',
        ),
        migrations.AlterField(
            model_name='category',
            name='name',
            field=models.CharField(max_length=255),
        ),
    ]
