# Generated by Django 5.1.3 on 2024-11-21 18:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ExpenseSystem', '0003_userprofile_profile'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userprofile',
            old_name='profile',
            new_name='profile_image',
        ),
    ]
