# Generated by Django 5.1.3 on 2024-11-27 13:33

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ExpenseSystem', '0005_remove_userprofile_profile_image_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='savings',
            name='date',
        ),
        migrations.RemoveField(
            model_name='savings',
            name='fund_source',
        ),
        migrations.AddField(
            model_name='savings',
            name='current_savings',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='savings',
            name='total_expense',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='savings',
            name='total_income',
            field=models.FloatField(default=0.0),
        ),
        migrations.AlterField(
            model_name='savings',
            name='amount',
            field=models.FloatField(default=0.0),
        ),
        migrations.AlterField(
            model_name='savings',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='first_name',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='last_name',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='profile_pic',
            field=models.ImageField(blank=True, upload_to='profile_pics/'),
        ),
    ]
