# Generated by Django 5.1.3 on 2024-11-28 02:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ExpenseSystem', '0006_remove_savings_date_remove_savings_fund_source_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='savings',
            name='amount',
        ),
    ]
