# Generated by Django 5.1.3 on 2024-11-28 05:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ExpenseSystem', '0008_customuser_profile'),
    ]

    operations = [
        migrations.DeleteModel(
            name='CustomUser',
        ),
    ]
